// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using crowdience.Models;

namespace crowdience.Migrations
{
    [DbContext(typeof(CrowdienceContext))]
    [Migration("20190325113704_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("crowdience.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("coupleOneName");

                    b.Property<string>("coupleTwoName");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("crowdience.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CoupleOneVote");

                    b.Property<string>("CoupleTwoVote");

                    b.Property<int>("GameId");

                    b.Property<string>("QuestionTitle");

                    b.Property<int>("VoteOneTotal");

                    b.Property<int>("VoteTwoTotal");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("crowdience.Models.Question", b =>
                {
                    b.HasOne("crowdience.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
